# housing data

I'll choose regression to be the prediction model because it's impossible/hard to set 1000 classifications/subsets from 1000 data.

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("housing_data.csv")
df

,Area,No. of Rooms,No. of Bathrooms,Location,Miles (dist. between school and house),Rent Price per Month,Sell Price
0,1360,1,1,Rural,463,7401,74446632
1,1794,3,1,Suburb,210,9259,76199794
2,1630,2,1,Suburb,157,16469,16249579
3,1595,1,1,Suburb,133,18096,24291317
4,2138,1,1,Suburb,10,9923,50273384
...,...,...,...,...,...,...,...
995,1375,1,1,City Center,33,16039,8670492
996,1262,2,1,City Center,38,9904,20223887
997,1702,3,1,Rural,180,13260,76086163
998,1705,3,1,Rural,418,6504,38329598
999,1163,1,1,Rural,237,15813,68023737

In [2]:
# Translate text format to symbol(int) format
df["Location"] = df["Location"].map({"City Center":0, "Suburb":1, "Rural":2}).astype('int')
df

,Area,No. of Rooms,No. of Bathrooms,Location,Miles (dist. between school and house),Rent Price per Month,Sell Price
0,1360,1,1,2,463,7401,74446632
1,1794,3,1,1,210,9259,76199794
2,1630,2,1,1,157,16469,16249579
3,1595,1,1,1,133,18096,24291317
4,2138,1,1,1,10,9923,50273384
...,...,...,...,...,...,...,...
995,1375,1,1,0,33,16039,8670492
996,1262,2,1,0,38,9904,20223887
997,1702,3,1,2,180,13260,76086163
998,1705,3,1,2,418,6504,38329598
999,1163,1,1,2,237,15813,68023737

# Sell Price Prediction for example

In [3]:
# Select X and y (sell price)
X = df.iloc[:,0:5]
y = df.iloc[:,6]

In [4]:
# Create predict dataset
predictdata = {"Area":[3000,100,3000], "No. of Rooms":[2,1,4], "No. of Bathrooms":[1,1,2], "Location":[0,1,2], "Miles (dist. between school and house)":[10,50,350]}
predictdatadf = pd.DataFrame(predictdata)
predictdatadf

,Area,No. of Rooms,No. of Bathrooms,Location,Miles (dist. between school and house)
0,3000,2,1,0,10
1,100,1,1,1,50
2,3000,4,2,2,350

In [5]:
# Linear
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X, y)
print(reg.predict(predictdatadf))

[40354063.56545261 37551225.88629698 45407154.51778489]

# Idea: Find similar data by house 1's features

In [6]:
df[df["Area"] == 3000]

Empty DataFrame
Columns: [Area, No. of Rooms, No. of Bathrooms, Location, Miles (dist. between school and house), Rent Price per Month, Sell Price]
Index: []

In [7]:
df[df["No. of Rooms"] == 2]

,Area,No. of Rooms,No. of Bathrooms,Location,Miles (dist. between school and house),Rent Price per Month,Sell Price
2,1630,2,1,1,157,16469,16249579
9,1982,2,1,2,200,16704,54206785
10,2635,2,1,2,76,16343,38469420
11,630,2,1,0,13,17867,72977550
18,1455,2,1,1,30,8222,25214047
...,...,...,...,...,...,...,...
980,701,2,1,0,267,7776,44837854
981,2860,2,1,0,479,9645,27384981
989,885,2,1,0,120,19691,16387155
990,974,2,1,2,111,15359,61901099
996,1262,2,1,0,38,9904,20223887

In [8]:
df[df["No. of Bathrooms"] == 1]

,Area,No. of Rooms,No. of Bathrooms,Location,Miles (dist. between school and house),Rent Price per Month,Sell Price
0,1360,1,1,2,463,7401,74446632
1,1794,3,1,1,210,9259,76199794
2,1630,2,1,1,157,16469,16249579
3,1595,1,1,1,133,18096,24291317
4,2138,1,1,1,10,9923,50273384
...,...,...,...,...,...,...,...
995,1375,1,1,0,33,16039,8670492
996,1262,2,1,0,38,9904,20223887
997,1702,3,1,2,180,13260,76086163
998,1705,3,1,2,418,6504,38329598
999,1163,1,1,2,237,15813,68023737

In [9]:
df[df["Location"] == 0]

,Area,No. of Rooms,No. of Bathrooms,Location,Miles (dist. between school and house),Rent Price per Month,Sell Price
7,1738,3,1,0,352,17023,51362588
8,830,3,1,0,137,17950,40783890
11,630,2,1,0,13,17867,72977550
12,2185,1,1,0,451,8745,63413770
13,1269,1,1,0,418,12091,62692404
...,...,...,...,...,...,...,...
981,2860,2,1,0,479,9645,27384981
985,2791,3,1,0,147,7788,35969114
989,885,2,1,0,120,19691,16387155
995,1375,1,1,0,33,16039,8670492
996,1262,2,1,0,38,9904,20223887

In [10]:
df[df["Miles (dist. between school and house)"] == 10]

,Area,No. of Rooms,No. of Bathrooms,Location,Miles (dist. between school and house),Rent Price per Month,Sell Price
4,2138,1,1,1,10,9923,50273384
275,2574,3,1,0,10,18602,48812486
690,1973,1,1,0,10,18905,43841814

According to above filters, I think the predicted house 1 price ... (please finish the story of house 1. Similar to houses 2 and 3.)

In [11]:
# You may try polynomial regression
# Polynomial power = 2
from sklearn.preprocessing import PolynomialFeatures
poly_reg2 = PolynomialFeatures(degree = 2)
X_poly = poly_reg2.fit_transform(X)
regp2 = LinearRegression()
regp2.fit(X_poly, y)


predictdatadf_poly = poly_reg2.fit_transform(predictdatadf)
print(regp2.predict(predictdatadf_poly))

[31856432.25409437 36333462.67973305 65664465.44183047]

In [12]:
# Polynomial power = 3
from sklearn.preprocessing import PolynomialFeatures
poly_reg3 = PolynomialFeatures(degree = 3)
X_poly = poly_reg3.fit_transform(X)
regp3 = LinearRegression()
regp3.fit(X_poly, y)


predictdatadf_poly = poly_reg3.fit_transform(predictdatadf)
print(regp3.predict(predictdatadf_poly))

[3.79216360e+07 1.63631304e+07 2.60302965e+08]