In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('http://bit.ly/kaggletrain')
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [2]:
df['Sex_Code'] = df['Sex'].map({'female':1, 'male':0}).astype('int')
df['Sex'] = df['Sex_Code']
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_Code
0,1,0,3,"Braund, Mr. Owen Harris",0,22.000000,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.000000,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",1,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.000000,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",0,35.000000,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.000000,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.000000,0,0,112053,30.0000,B42,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,29.699118,1,2,W./C. 6607,23.4500,NaN,S,1
889,890,1,1,"Behr, Mr. Karl Howell",0,26.000000,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",0,32.000000,0,0,370376,7.7500,NaN,Q,0

In [3]:
X = df[["Pclass", "Sex", "Age"]]
y = df["Survived"]

In [4]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X,y)
Jack = clf.predict([[3, 0, 23.0]])
print("Jack", Jack)
Rose = clf.predict([[1, 1, 20.0]])
print("Rose", Rose)

Jack [0]
Rose [1]

In [5]:
# K-NN
from sklearn import neighbors
clf = neighbors.KNeighborsClassifier()
clf.fit(X,y)
Jack = clf.predict([[3, 0, 23.0]])
print("Jack", Jack)
Rose = clf.predict([[1, 1, 20.0]])
print("Rose", Rose)

Jack [0]
Rose [1]

In [6]:
# SVC
from sklearn import svm
clf = svm.SVC()
clf.fit(X,y)
Jack = clf.predict([[3, 0, 23.0]])
print("Jack", Jack)
Rose = clf.predict([[1, 1, 20.0]])
print("Rose", Rose)

Jack [0]
Rose [0]

In [7]:
# Gaussian Naive bayes
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X,y)
Jack = clf.predict([[3, 0, 23.0]])
print("Jack", Jack)
Rose = clf.predict([[1, 1, 20.0]])
print("Rose", Rose)

Jack [0]
Rose [1]

In [8]:
# Multinomail Naive bayes
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X,y)
Jack = clf.predict([[3, 0, 23.0]])
print("Jack", Jack)
Rose = clf.predict([[1, 1, 20.0]])
print("Rose", Rose)

Jack [0]
Rose [1]

In [9]:
# Decision Tree
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf.fit(X,y)
Jack = clf.predict([[3, 0, 23.0]])
print("Jack", Jack)
Rose = clf.predict([[1, 1, 20.0]])
print("Rose", Rose)

Jack [0]
Rose [1]

In [10]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(X,y)
Jack = clf.predict([[3, 0, 23.0]])
print("Jack", Jack)
Rose = clf.predict([[1, 1, 20.0]])
print("Rose", Rose)

Jack [0]
Rose [1]

In [11]:
# XGBoost
from xgboost.sklearn import XGBClassifier
clf = XGBClassifier()
clf.fit(X,y)
two = {"Pclass":[3,1], "Sex":[0,1], "Age":[23.0,20.0]}
df1 = pd.DataFrame(two)
#Jack = clf.predict([[3, 0, 23.0]])
Jack = clf.predict(df1.iloc[0:1])
print("Jack", Jack)
Rose = clf.predict(df1.iloc[1:2])
print("Rose", Rose)

Jack [0]
Rose [1]

## Practice
If we respectively use max age and min age to replace empty age, will the results of Jack and Rose change?